server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    # MySQL 8.0 连接地址
    url: jdbc:mysql://localhost:3306/examdb?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8mb4
    # MySQL 8.0 驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库用户名和密码
    username: root  # 替换为您的MySQL用户名
    password: MySQL!@34  # 替换为您的MySQL密码
    schema: classpath:schema.sql
  h2:
    console:
      enabled: false  # 关闭H2控制台
  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.examsystembackend.entity
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

logging:
  level:
    root: info
    com.example.examsystembackend: debug